# Generated by Django 5.0.6 on 2024-05-12 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('face_path', models.CharField(max_length=100)),
                ('entered_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('recording_id', models.AutoField(primary_key=True, serialize=False)),
                ('recording_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event_recordings',
            fields=[
                ('recording_id', models.AutoField(primary_key=True, serialize=False)),
                ('recording_path', models.CharField(max_length=100)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.events')),
            ],
        ),
    ]
